spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.140.6:3306/pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tDwQH5RGmEvMgMktUPL
      secret-key: XdhggtekSrO4fwAhuS3KCyBab5P0uo
      oss:
        endpoint: https://oss-cn-beijing.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #全局的逻辑删除规则
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10002

logging:
  level:
    com.dzd.product: debug
