#开启服务注册发现中心的地址，并且规定该模块在服务发现中心的名字
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_root
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_root2
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=api/?(?<segment>.*),/$\{segment}
            # /api/product/** -> /prodcut/**
        - id: third-party_route
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}
        - id: admin_route
          #lb 为负载均衡
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}
            #     /api/captcha.jpg  -> http://localhost:8080/renren-fast/captcha.jpg



server:
  port: 88


